spring:
  datasource:
    url: jdbc:h2:mem:jogosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update  # 'update' mantém dados e cria tabelas novas automaticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
